{
  "family": "kudiapp-task",
  "networkMode": "awsvpc",
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "512",
  "memory": "1024",
  "runtimePlatform": {
    "cpuArchitecture": "X86_64",
    "operatingSystemFamily": "LINUX"
  },
  "containerDefinitions": [
    {
      "name": "kudiapp",
      "image": "<IMAGE_NAME>",
      "essential": true,
      "portMappings": [
        {
          "containerPort": 8083,
          "protocol": "tcp"
        }
      ],
      "environment": [
        {"name": "SERVER_PORT", "value": "8083"},
        {"name": "APP_EMAIL_URL", "value": "SECRET_APP_EMAIL_URL"},
        {"name": "APP_JWT_SECRET", "value": "SECRET_APP_JWT_SECRET"},
        {"name": "APP_JWT_EXPIRATION_MS", "value": "86400000"},
        {"name": "APP_JWT_REFRESH_EXPIRATION_MS", "value": "604800000"},
        {"name": "MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE", "value": "health,info"},
        {"name": "MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS", "value": "always"},
        {"name": "MANAGEMENT_ENDPOINT_HEALTH_ACCESS", "value": "unrestricted"},
        {"name": "MANAGEMENT_ENDPOINT_INFO_ACCESS", "value": "unrestricted"},
        {"name": "SPRING_DATASOURCE_URL", "value": "SECRET_SPRING_DATASOURCE_URL"},
        {"name": "SPRING_DATASOURCE_USERNAME", "value": "SECRET_SPRING_DATASOURCE_USERNAME"},
        {"name": "SPRING_DATASOURCE_PASSWORD", "value": "SECRET_SPRING_DATASOURCE_PASSWORD"},
        {"name": "SPRING_DATASOURCE_DRIVER_CL