name: Build, Push, and Security Scan

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kudi9ja/kudiapp:kudiappapi

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker login
        run: docker info | grep Username || echo "⚠️ Docker login failed"

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image to DockerHub
        run: docker push $IMAGE_NAME

      - name: Install Trivy for security scan
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.61.0/trivy_0.61.0_Linux-64bit.tar.gz
          tar -xf trivy_0.61.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Security Scan with Trivy
        run: |
          echo "===== Scanning Image =====" > trivy_report.txt
          trivy image --exit-code 0 --severity CRITICAL,HIGH $IMAGE_NAME >> trivy_report.txt

      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: TrivyScanResults
          path: trivy_report.txt
